package common.protocol.command;

import java.io.Serializable;

public enum CommandType implements Serializable {
    PING,

    // Login
    LOGIN,
    FORGOT_PASSWORD,
    CHANGE_PASSWORD,

    // Quản lý phòng
    GET_ALL_ROOMS,
    GET_ROOM_BY_ID,
    SEARCH_ROOMS,
    ADD_ROOM,
    UPDATE_ROOM_INFORMATION,
    GET_ALL_ROOM_TYPES,
    GET_ROOM_TYPE_BY_ID,
    UPDATE_ROOM_TYPE_PRICING,

    // Quản lý đặt phòng
    BOOK_ROOM,
    BOOK_MULTI_ROOMS,

    GET_PENDING_BOOKING,
    GET_PENDING_BOOKINGS_OF_ROOM,
    GET_ACTIVE_CHECKIN_INFO,
    GET_ACTIVE_STAY_TIMES,

    CHECK_IN_BY_ODR_ID,
    CANCEL_BOOKING_BY_ODR_ID,
    CANCEL_BOOKING,

    CHECK_IN,
    CHECK_OUT,

    EXTEND_ROOM,

    CHANGE_ROOM_BEFORE_CHECKIN,
    CHANGE_ROOM_WHILE_CHECKIN,

    ADD_SERVICE_TO_ROOM,
    GET_ROOM_CALENDAR,

    GET_RECOMMEND_ROOMS,
    CALCULATE_ROOM_FEE,
    CALCULATE_ROOM_FEE_WITH_NEW_ROOM,

    // Quản lý khách hàng
    GET_ALL_CUSTOMERS,
    GET_CUSTOMER_BY_ID,
    SEARCH_CUSTOMERS,
    ADD_CUSTOMER,
    UPDATE_CUSTOMER,
    GET_CUSTOMER_BY_PHONE,

    // Quản lý nhân viên
    GET_ALL_EMPLOYEES,
    GET_EMPLOYEE_BY_ID,
    ADD_EMPLOYEE,
    UPDATE_EMPLOYEE,
    GET_ALL_EMPLOYEE_TYPES,
    GET_EMPLOYEES_BY_TYPE,
    DELETE_EMPLOYEE,

    // Quản lý dịch vụ
    GET_ALL_SERVICES,
    GET_SERVICES_BY_TYPE,
    GET_SERVICE_BY_ID,
    ADD_SERVICE,
    UPDATE_SERVICE,
    INCREASE_SERVICE_QUANTITY,
    DELETE_SERVICE,

    // Quản lý khuyến mãi
    GET_ALL_PROMOTIONS,
    GET_PROMOTION_BY_ID,
    ADD_PROMOTION,
    UPDATE_PROMOTION,
    DELETE_PROMOTION,

    // Quản lý hóa đơn
    GET_ALL_ORDERS,
    GET_ORDER_BY_ID,
    GET_ORDERS_BY_STATUS,
    GET_ORDER_ROOM_LINES,
    GET_ORDER_SERVICE_LINES,
    UPDATE_ORDER_PROMOTION,
    SEARCH_ORDERS,
    PAY_ORDER,

    // Thống kê
    GET_SERVICE_RANKING,
    GET_BOOKING_TYPE_REVENUE,
    GET_ORDER_STATISTICS,

    // Dashboard
    GET_DASHBOARD_DATA,
    GET_DASHBOARD_OVERVIEW,
    SAVE_DASHBOARD_PLAN_NOTE,
    SAVE_DASHBOARD_ALERT_NOTE,

    // Do Nothing
    UNKNOWN
}